version: "3"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=pet_monitor_db
  web:
    build: .
    container_name: face_recognition_web
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_URL=mongodb://root:pass@mongo:27017/
    ports:
      - 5000:5001
    depends_on: 
      - mongodb
